// axgate-pack：把 libaxvm.so（或 PIC flat 镜像）打成 blob / 可链接 .c
//
// UW2：AES wrap mask = SHA256(uk_seed || "UW2" || pkg || 0 || cert || meta)
// uk_seed 仅以打散 uint64 存入 host；运行时必须由 hxboot prime 注入 APK 身份。
package main

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"flag"
	"fmt"
	"os"
	"strings"
)

const (
	version   = 0x00010001
	descSize  = 112
	apiXorKey = 0x3C
	ukXor     = 0xD00DF00DD00DF00D

	flagAntiDebug = 0x1
	flagIntegrity = 0x2
	flagIatCrypt  = 0x4
	flagAesCtr    = 0x8
	flagFlatOep   = 0x10
	flagMemfdElf  = 0x20
	flagAxzc      = 0x40
	flagKeyWrap   = 0x80
)

var apiNames = []string{
	"mmap", "mprotect", "munmap", "memfd_create", "ftruncate",
	"open", "read", "close", "ptrace",
}

func xorNames(key byte, names []string) []byte {
	var out []byte
	for _, n := range names {
		b := []byte(n)
		enc := make([]byte, len(b))
		for i := range b {
			enc[i] = b[i] ^ byte(key+byte(i))
		}
		out = append(out, enc...)
		out = append(out, 0)
	}
	return out
}

func deriveMagic(ukSeed []byte) uint32 {
	h := sha256.Sum256(append(append([]byte{}, ukSeed...), []byte("AG")...))
	m := binary.LittleEndian.Uint32(h[:4])
	if m == 0 {
		m = 0xA71C3E59
	}
	return m
}

func wrapMaskUW2(ukSeed []byte, pkg string, cert []byte, imageSize, reserved1 uint32, sha []byte) []byte {
	buf := make([]byte, 0, 32+4+len(pkg)+1+32+4+4+16)
	buf = append(buf, ukSeed...)
	buf = append(buf, 'U', 'W', '2', 0)
	buf = append(buf, []byte(pkg)...)
	buf = append(buf, 0)
	buf = append(buf, cert...)
	var le [4]byte
	binary.LittleEndian.PutUint32(le[:], imageSize)
	buf = append(buf, le[:]...)
	binary.LittleEndian.PutUint32(le[:], reserved1)
	buf = append(buf, le[:]...)
	buf = append(buf, sha[:16]...)
	sum := sha256.Sum256(buf)
	return sum[:]
}

func emitC(path string, blob []byte) error {
	var b strings.Builder
	b.WriteString("/* auto-generated by axgatepack — do not edit */\n")
	b.WriteString("#include <stdint.h>\n\n")
	b.WriteString("__attribute__((aligned(16), used))\n")
	b.WriteString("const uint8_t axgate_section[] = {\n")
	for i, v := range blob {
		if i%16 == 0 {
			b.WriteString("  ")
		}
		fmt.Fprintf(&b, "0x%02x,", v)
		if i%16 == 15 || i == len(blob)-1 {
			b.WriteString("\n")
		} else {
			b.WriteString(" ")
		}
	}
	b.WriteString("};\n\n")
	fmt.Fprintf(&b, "const uint32_t axgate_section_size = %d;\n", len(blob))
	return os.WriteFile(path, []byte(b.String()), 0644)
}

func emitUk(path string, ukSeed []byte, magic uint32) error {
	var b strings.Builder
	b.WriteString("/* auto-generated — scattered uk_seed; full key needs runtime APK identity */\n")
	b.WriteString("#include <stdint.h>\n\n")
	b.WriteString("const uint64_t axgate_uk_q[4] = {\n  ")
	for i := 0; i < 4; i++ {
		v := binary.LittleEndian.Uint64(ukSeed[i*8 : i*8+8])
		v ^= ukXor
		fmt.Fprintf(&b, "0x%016xull", v)
		if i != 3 {
			b.WriteString(", ")
		}
	}
	b.WriteString("\n};\n\n")
	fmt.Fprintf(&b, "const uint32_t axgate_desc_magic = 0x%08xu;\n", magic)
	return os.WriteFile(path, []byte(b.String()), 0644)
}

func main() {
	inPath := flag.String("in", "", "input image (libaxvm.so or flat PIC)")
	outPath := flag.String("out", "axgate_blob.bin", "output binary blob")
	cPath := flag.String("c", "", "optional: emit linkable .c with blob array")
	ukPath := flag.String("uk", "", "emit host uk_seed .c")
	mode := flag.String("mode", "memfd", "memfd|flat")
	oep := flag.Uint64("oep", 0, "flat mode OEP RVA")
	noAnti := flag.Bool("no-antidebug", false, "omit TracerPid gate (LSPosed-friendly)")
	noCompress := flag.Bool("no-compress", false, "skip AXZC before AES")
	apkPkg := flag.String("apk-pkg", "", "module package (required for UW2 wrap)")
	apkCert := flag.String("apk-cert-sha256", "", "module cert SHA-256 hex (required for UW2 wrap)")
	flag.Parse()
	if *inPath == "" || *apkPkg == "" || *apkCert == "" {
		fmt.Fprintln(os.Stderr, "usage: axgatepack -in <image> -apk-pkg P -apk-cert-sha256 HEX [-uk out.c] ...")
		os.Exit(2)
	}
	if *ukPath == "" {
		if *cPath != "" {
			*ukPath = strings.TrimSuffix(*cPath, ".c") + "_uk.c"
		} else {
			*ukPath = strings.TrimSuffix(*outPath, ".bin") + "_uk.c"
		}
		if *ukPath == "" || *ukPath == "_uk.c" {
			*ukPath = "axgate_uk.c"
		}
	}

	cert, err := hex.DecodeString(strings.TrimSpace(*apkCert))
	if err != nil || len(cert) != 32 {
		panic("apk-cert-sha256 must be 32-byte hex")
	}

	plain, err := os.ReadFile(*inPath)
	if err != nil {
		panic(err)
	}

	payload := plain
	compLen := uint32(0)
	useAxzc := !*noCompress
	if useAxzc {
		compressed := axzcCompress(plain)
		roundtrip, err := axzcInflate(compressed, len(plain))
		if err != nil || len(roundtrip) != len(plain) {
			panic("axzc roundtrip failed")
		}
		for i := range plain {
			if roundtrip[i] != plain[i] {
				panic("axzc roundtrip mismatch")
			}
		}
		if len(compressed) < len(plain) {
			payload = compressed
			compLen = uint32(len(compressed))
		} else {
			useAxzc = false
			fmt.Printf("axgatepack: axzc skipped (no gain: %d >= %d)\n", len(compressed), len(plain))
		}
	}

	ukSeed := make([]byte, 32)
	if _, err := rand.Read(ukSeed); err != nil {
		panic(err)
	}
	magic := deriveMagic(ukSeed)

	key := make([]byte, 16)
	iv := make([]byte, 16)
	if _, err := rand.Read(key); err != nil {
		panic(err)
	}
	if _, err := rand.Read(iv); err != nil {
		panic(err)
	}

	block, err := aes.NewCipher(key)
	if err != nil {
		panic(err)
	}
	ct := make([]byte, len(payload))
	cipher.NewCTR(block, iv).XORKeyStream(ct, payload)
	sum := sha256.Sum256(plain)

	mask := wrapMaskUW2(ukSeed, *apkPkg, cert, uint32(len(plain)), compLen, sum[:])
	keyWrap := make([]byte, 32)
	for i := 0; i < 16; i++ {
		keyWrap[i] = key[i] ^ mask[i]
		keyWrap[16+i] = iv[i] ^ mask[16+i]
	}

	nameTab := xorNames(apiXorKey, apiNames)
	nameOff := uint32(descSize)
	imageOff := nameOff + uint32(len(nameTab))
	for imageOff%16 != 0 {
		nameTab = append(nameTab, 0)
		imageOff = nameOff + uint32(len(nameTab))
	}

	flags := uint32(flagIntegrity | flagIatCrypt | flagAesCtr | flagKeyWrap)
	if !*noAnti {
		flags |= flagAntiDebug
	}
	if useAxzc {
		flags |= flagAxzc
	}
	switch *mode {
	case "flat":
		flags |= flagFlatOep
	default:
		flags |= flagMemfdElf
		*mode = "memfd"
	}

	buf := make([]byte, int(imageOff)+len(ct))
	binary.LittleEndian.PutUint32(buf[0:], magic)
	binary.LittleEndian.PutUint32(buf[4:], version)
	binary.LittleEndian.PutUint32(buf[8:], flags)
	binary.LittleEndian.PutUint32(buf[12:], 0)
	binary.LittleEndian.PutUint32(buf[16:], uint32(len(plain)))
	binary.LittleEndian.PutUint32(buf[20:], imageOff)
	binary.LittleEndian.PutUint32(buf[24:], nameOff)
	binary.LittleEndian.PutUint32(buf[28:], uint32(len(nameTab)))
	copy(buf[32:64], keyWrap)
	copy(buf[64:96], sum[:])
	binary.LittleEndian.PutUint64(buf[96:], *oep)
	binary.LittleEndian.PutUint32(buf[104:], apiXorKey)
	binary.LittleEndian.PutUint32(buf[108:], compLen)
	copy(buf[nameOff:], nameTab)
	copy(buf[imageOff:], ct)

	if err := os.WriteFile(*outPath, buf, 0644); err != nil {
		panic(err)
	}
	if err := emitUk(*ukPath, ukSeed, magic); err != nil {
		panic(err)
	}
	if *cPath != "" {
		if err := emitC(*cPath, buf); err != nil {
			panic(err)
		}
	}
	ratio := 100.0
	if len(plain) > 0 {
		ratio = float64(len(ct)) * 100.0 / float64(len(plain))
	}
	fmt.Printf("axgatepack: wrote %s (%d B) mode=%s plain=%d cipher=%d axzc=%v uw2=1 magic=%08x ratio=%.1f%%\n",
		*outPath, len(buf), *mode, len(plain), len(ct), useAxzc, magic, ratio)
	fmt.Printf("axgatepack: wrote %s (scattered uk_seed)\n", *ukPath)
	if *cPath != "" {
		fmt.Printf("axgatepack: wrote %s\n", *cPath)
	}
}
